// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahcozjuhotxbyyisilmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoY296anVob3R4Ynl5aXNpbG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODk4MjEsImV4cCI6MjA2NjE2NTgyMX0.YeOno2H9EdRWBzuk0veaoScI4cFdFc6nWRKHYrXoZKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);